- django_declarative_apis/machinery/filtering.py
- tests/machinery/test_base.py
> Fix filters for classes with mixins

- CHANGELOG.md
- django_declarative_apis/authentication/oauthlib/oauth1.py
- django_declarative_apis/authentication/oauthlib/request_validator.py
- django_declarative_apis/machinery/__init__.py
- django_declarative_apis/machinery/errors.py
- django_declarative_apis/machinery/utils.py
- django_declarative_apis/resources/resource.py
- tests/authentication/oauthlib/test_oauth1.py
- tests/authentication/oauthlib/test_request_validator.py
- tests/machinery/test_base.py
> remove use of root logger

- CHANGELOG.md
- setup.py
> added long_description

- contributing.md
Hi! I saw your article on Stack Overflow and decided to take a look. Just wanted to fix 2 tiny typos in `contributing.md`
> Fix typos in contributing.md

- CHANGELOG.md
- django_declarative_apis/machinery/__init__.py
- example/example/settings.py
- example/manage.py
- example/myapp/models.py
- example/myapp/resources.py
- example/myapp/urls.py
We should probably have an automated test in the examples app.
> Various fixes to bring the example app up to speed

- CHANGELOG.md
- requirements-dev.txt
Update
- flake8
- bandit
- ipython
> chore: update easy dev dependencies

- CHANGELOG.md
- django_declarative_apis/authentication/__init__.py
- django_declarative_apis/authentication/oauthlib/endpoint.py
- django_declarative_apis/machinery/__init__.py
- example/myapp/resources.py
- requirements-dev.txt
Update Black dev dependency.
There is a bug in 19.3b0 which may cause problems locally.  psf/black#875
> chore: update black

- .bumpversion.cfg
- .github/workflows/release.yml
- docs/source/conf.py
- setup.py
This PR will automate deployments to PyPI and Github pages. Read the docs integration to follow at a later date.
> Adding release automation

- requirements-dev.txt
- Update Black to stable version (requires no formatting update)
- Update coverage
- Update flake8
- Update pyyaml
> Update easy dev requirements

- .github/workflows/tests.yml
- django_declarative_apis/authentication/__init__.py
- django_declarative_apis/resources/resource.py
Run tests and static analysis as a PR check using GitHub actions
> chore: Run tests and static analysis as a PR check using GitHub actions

- .bumpversion.cfg
- CHANGELOG.md
- docs/source/conf.py
- setup.py
> Release 0.23.0

- .github/workflows/publish-release.yml
- CHANGELOG.md
> fix: Fix GitHub publish action

- .bumpversion.cfg
- docs/source/conf.py
- setup.py
> release: Release 0.23.1

- contributing.md
contributing.md has a couple old links and names. This updates them.
> update contributing doc

- .github/workflows/publish-release.yml
- CHANGELOG.md
> Bump versions and fix typo in publish-release github action

- .readthedocs.yaml
- CHANGELOG.md
- pull_request_template.md
> Fix ReadTheDocs documentation build with pyproject.toml

- .readthedocs.yaml
> ReadTheDocs only supports up to Python 3.8

- .readthedocs.yaml
- CHANGELOG.md
> Use new .readthedocs.yaml format

- CHANGELOG.md
- django_declarative_apis/authentication/oauthlib/endpoint.py
- pyproject.toml
> chore(deps): Allow cryptography >3.4.8

- .bumpversion.cfg
- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
- Bump the version
- Update the CHANGELOG
> release: Release 0.25.0

- .bumpversion.cfg
- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
- Fix README for publishing
- Update CHANGELOG
> release: Release 0.25.1

- CHANGELOG.md
- docs/source/filters.rst
> docs: Fix typo

- .bumpversion.cfg
- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
> 0.25.2 release

- .bumpversion.cfg
- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
> 0.25.3 release

- django_declarative_apis/resources/utils.py
- tests/resources/test_resource.py
> fix: remove outdated httpresponse wrapper

- .bumpversion.cfg
- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
> chore: bump to 0.29.0

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/machinery/filtering.py
- docs/source/conf.py
- pyproject.toml
- tests/filters.py
- tests/machinery/test_base.py
- tests/models.py
> fix:filter caching for unhashable types

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/machinery/__init__.py
- docs/source/conf.py
- pyproject.toml
> finalize endpoints before dispatching async tasks

- CHANGELOG.md
- django_declarative_apis/machinery/attributes.py
> Docs: Correct imports in code-blocks

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/resources/resource.py
- docs/source/conf.py
- pyproject.toml
> clean up debugging logs

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/machinery/filtering.py
- docs/source/conf.py
- pyproject.toml
- tests/filters.py
- tests/test_filters.py
- tests/tests.py
> add ExpandableGeneric filter type

- .bumpversion.cfg
- CHANGELOG.md
- docs/source/conf.py
- pyproject.toml
> chore: Release django-declarative-apis-0.31.7 (@W-14178534)

- .github/workflows/tests.yml
- CHANGELOG.md
> Update github action versions

- CHANGELOG.md
- Makefile
> fix: Fix Makefile install target

- .github/workflows/publish-release.yml
> chore: update publish workflow

- .bumpversion.cfg
- docs/source/conf.py
- pyproject.toml
Work Item: [W-18078839](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18128971)
----
> chore: release v0.33.0 @W-18128971
