salesforce/django-declarative-apis

- setup.py
Required because PyPI disallows re-use of the same filename
> Bump version to 0.18.4

- .bumpversion.cfg
- docs/source/conf.py
> Bringing bumpversion config and docs version up to date

- django_declarative_apis/machinery/tasks.py
- requirements.txt
- setup.py
Doesn't break backwards compatibility with previous versions of celery. Seems that types were previously serialized, but that's no longer the case.
> Fix to allow for most recent celery version

- CHANGELOG.md
- requirements-dev.txt
Resolves GitHub security warning.
>Remediation
>Upgrade pyyaml to version 4.2b1 or later. For example:
> pyyaml>=4.2b1
This is a dev dependency, so I don't see why we shouldn't upgrade to the latest.
> Update pyyaml dev requirement to fix GitHub security warning

- CHANGELOG.md
- example/requirements.txt
- requirements.txt
Updating to Django 2.2 will come next, but we might as well fix this warning since it's easy.
> Bump Django patch version to fix GitHub security warning

- .bumpversion.cfg
- CHANGELOG.md
- Makefile
- django_declarative_apis/machinery/attributes.py
- django_declarative_apis/machinery/tasks.py
- docs/source/conf.py
* Add a make target for testing with deprecation warnings turned on
* Fix the deprecation warnings found (mostly `logger.warn` -> `logger.warning`)
* Fix a couple of missed version numbers.
> Fix deprecation warnings and version numbers

- .bumpversion.cfg
- CHANGELOG.md
- Makefile
- django_declarative_apis/machinery/attributes.py
- django_declarative_apis/machinery/tasks.py
- docs/source/conf.py
* Add a make target for testing with deprecation warnings turned on
* Fix the deprecation warnings found (mostly logger.warn -> logger.warning)
* Fix a couple of missed version numbers.
> Fix deprecation warnings and versions

- CHANGELOG.md
- Makefile
- requirements-dev.txt
- requirements.txt
* Add Make targets for Black formatting, but don't actually format the codebase yet.
* Add Black as a dev dependency
* Sort requirements.txt and requirements-dev.txt, but don't change any dependencies (other than Black)
> Add Makefile targets for Black code formatter

- CHANGELOG.md
- django_declarative_apis/authentication/__init__.py
- django_declarative_apis/authentication/oauthlib/oauth1.py
- django_declarative_apis/machinery/__init__.py
- django_declarative_apis/resources/emitters.py
- django_declarative_apis/resources/resource.py
- django_declarative_apis/resources/utils.py
- example/myapp/resources.py
Hopefully this set of flake8 fixes is uncontroversial.
There are a few more "unused local variable" warnings that I'll have to look at more closely.
Next, I'll tackle a raft of "unused import" errors.  I saw test errors when doing the obvious thing and just removing all the unused imports, so I'll have to try again more carefully.
> Fix uncontroversial flake8 warnings

- CHANGELOG.md
- tests/resources/test_emitters.py
Use yaml's `safe_load` to avoid deprecation warning:
```
/Users/robert.grant/projects/django-declarative-apis/tests/resources/test_emitters
.py:156: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
self.assertEqual(yaml.load(em.render(None)), data)
```
> Use yaml's `safe_load`

- CHANGELOG.md
- django_declarative_apis/authentication/oauthlib/endpoint.py
- django_declarative_apis/authentication/oauthlib/oauth_errors.py
- django_declarative_apis/machinery/__init__.py
- django_declarative_apis/machinery/attributes.py
- django_declarative_apis/machinery/tasks.py
- django_declarative_apis/resources/emitters.py
- django_declarative_apis/resources/resource.py
- django_declarative_apis/resources/utils.py
- tests/authentication/oauthlib/test_request_validator.py
- tests/authentication/test_endpoint.py
- tests/filters.py
- tests/machinery/test_base.py
- tests/resources/test_emitters.py
- tests/resources/test_resource.py
- tests/resources/test_utils.py
- tests/test_adapters.py
- tests/views.py
* Don't import from `*` in `machinery.__init__`
This one might be a bit controversial.  The `import *` is replaced with a pretty long list of imports, but the `*` import obscured the fact that some base things like `logging` and `abc` weren't being imported in `machinery.__init__`, they were coming in from the `attributes` module.  There are a few attributes that aren't explicitly imported here that I could add to the list if the intention is for this module to be an interface that subsumes `attributes`.
* Remove unnecessary imports and sort them (PyCharm's "optimize imports")
* Wrap a couple of long lines
* Remove an unnecessary lambda
> flake8 - primarily fix up imports

- CHANGELOG.md
- example/myapp/admin.py
- example/myapp/tests.py
- example/myapp/views.py
Ignore specific "unused imports" in the example.  They're in files meant to be empty templates.
> Fix flake8 warnings in example

- CHANGELOG.md
- django_declarative_apis/resources/emitters.py
- example/requirements.txt
- requirements-dev.txt
- requirements.txt
- tests/testutils.py
* Bump Django to 2.0 - no changes needed
* Bump Django to 2.1
* Remove unneeded use of deprecated `models.permalink`
* "Invalid Signature" error on POST in test: It looks like Django's `urlencode()` behavior changed for `bytes`, and this is messing up the `oauth_signature` generated by `oauth2` (only used in testing): 
* https://code.djangoproject.com/ticket/28679
* https://docs.djangoproject.com/en/3.0/releases/2.0/#removed-support-for-bytestrings-in-some-places
* Bump Django to 2.2 - no changes needed
> Update to Django 2.2

- .travis.yml
- Makefile
- django_declarative_apis/authentication/oauthlib/oauth_errors.py
- django_declarative_apis/machinery/__init__.py
- django_declarative_apis/resources/emitters.py
- django_declarative_apis/resources/resource.py
- django_declarative_apis/resources/utils.py
- tests/machinery/test_base.py
- tests/testutils.py
Have TravisCI run `test-all` (`coverage`, `vuln-static`, and `formatcheck`) instead of just `test`.
I've removed the `static` target from the `test-all` target for now, because there are still outstanding flake8 errors.
Also, format the codebase with black again.  Since it hasn't been a requirement, the code didn't pass `formatcheck` anymore.
> Use the test-all target with TravisCI

- CHANGELOG.md
- requirements-dev.txt
- requirements.txt
Expand the allowable range of the `cryptography` dependency to include the latest (3.4.7).
Also update the `coverage` dev dependency to ~5.0, because it's giving me an error locally.
This attempts to address the Snyk warning (#51) as well.
> chore: update cryptography and coverage dependencies

- CHANGELOG.md
- requirements-dev.txt
- tests/authentication/oauthlib/test_oauth1.py
- tests/authentication/oauthlib/test_request_validator.py
- tests/machinery/test_base.py
- tests/resources/test_resource.py
- tests/resources/test_utils.py
- tests/test_filters.py
Remove dev dependency on [mock](https://pypi.org/project/mock/): Mock is a backport library for functionality that exists in Python 3.
Update the tests that use `mock` to use `unittest.mock`.
> chore: remove "mock" dev dependency

- .travis.yml
- CHANGELOG.md
Specifically, add Python 3.8 and 3.9 to our Travis CI testing.
> Test all Python versions currently in support.

- Makefile
pip 21 is more strict due to its dependency resolver.  We should ensure that we're using the latest pip when we install and test locally.
> chore: Upgrade pip as part of `make install`

- example/requirements.txt
- requirements.txt
Let's support both Django 2.2 and 3.2 until consumers of this package catch up.
> Don't drop support for Django 2.2 until consumers catch up

- CHANGELOG.md
We often forget to update the CHANGELOG in this repo.
Here I update the CHANGELOG for the current release by filling in missing entries.
> fix: Fill in missing CHANGELOG entries

- .github/workflows/tests.yml
- CHANGELOG.md
GitHub likes names without spaces better.
The GitHub Action works as it is currently names, but the PR check doesn't show up correctly in the branch protection dropdown.
> chore: remove spaces in name of `test` GitHub Action

- CHANGELOG.md
- README.md
- docs/source/index.rst
Add a docs badge to the README and make the docs title a little nicer.
See published docs at https://django-declarative-apis.readthedocs.io/en/stable/
> feat: Small updates for ReadTheDocs integration

- CHANGELOG.md
- django_declarative_apis/machinery/errors.py
- docs/source/conf.py
- pyproject.toml
- tests/machinery/test_base.py
- tests/machinery/test_errors.py
- tests/settings.py
- Let ServerError take an `additional_info` argument
- Use f-strings throughout errors.py
- Use enum value rather than bare int for an error code
- Add some unit tests for errors.py to bump up coverage
- Bump coverage check to 91%
- Fix a Sphinx configuration error that appears with a new version of Sphinx (to get the PR checks to pass)
> chore: Improve errors.py

- CHANGELOG.md
- django_declarative_apis/machinery/attributes.py
- requirements.txt
- tests/tests.py
- tests/urls.py
- tests/views.py
Allow supplying a Pydantic model as a field `type` for validation and coercion.
A big win: we can use a Pydantic model to validate the contents of a dict field value (not just that the value is a dict!)
> feat: Pydantic field validation

- .bumpversion.cfg
- CHANGELOG.md
- docs/source/conf.py
- setup.py
- Bump the version
- Update the CHANGELOG
> release: Release 0.24.0

- .github/workflows/tests.yml
- CHANGELOG.md
- pyproject.toml
Test against Python 3.11 in PR checks.
> Test against Python 3.11 in PR checks

- .readthedocs.yaml
- CHANGELOG.md
The ReadTheDocs build is failing based on me using `build.tools.python`:
https://readthedocs.org/projects/django-declarative-apis/builds/18794071/
The documentation led me to believe this was the right way to specify the Python version.  But, I'll try the old way.
https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version
> Try the old way of specifying the Python version

- CHANGELOG.md
- django_declarative_apis/authentication/oauthlib/endpoint.py
- pyproject.toml
A couple of methods were renamed in `oauthlib` 3.1.0:
- [Renamed `construct_base_string` to `signature_base_string`](https://github.com/oauthlib/oauthlib/commit/42023d8303113073e31a57e1bbf70216b7120e20)
- [Renamed `normalize_base_string_uri` to `base-string_uri`](https://github.com/oauthlib/oauthlib/commit/0ef0a9c4342dfee4bd3aef7d6d9fa09e7226a732#)
> chore(deps): Update oauthlib to >=3.1.0

- CHANGELOG.md
- django_declarative_apis/authentication/oauthlib/oauth1.py
- django_declarative_apis/authentication/oauthlib/oauth_errors.py
- django_declarative_apis/resources/resource.py
- tests/authentication/oauthlib/test_oauth1.py
- Handle "Malformed authorization header" `ValueError` that bubbles up from `oauthlib` the same way we handle other oauth errors
- Fix a docstring typo
> fix: Handle malformed auth header

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/machinery/filtering.py
- django_declarative_apis/models.py
- docs/source/conf.py
- pyproject.toml
- tests/filters.py
- tests/machinery/test_base.py
- tests/models.py
> feat: cache queries in filters

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/machinery/__init__.py
- django_declarative_apis/machinery/attributes.py
- django_declarative_apis/machinery/tasks.py
- docs/source/conf.py
- pyproject.toml
- tests/machinery/test_base.py
> feat: generic resource support

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/machinery/filtering.py
- docs/source/conf.py
- pyproject.toml
- tests/filters.py
- tests/machinery/test_base.py
> feat: cache functions and fake relations in filters

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/resources/utils.py
- docs/source/conf.py
- pyproject.toml
- tests/resources/test_resource.py
- tests/testutils.py
> feat: support alternate request charset (@W-14001583)

- CHANGELOG.md
- django_declarative_apis/machinery/attributes.py
> Docs: Correct documentation for default value of `required` on `field`

- CHANGELOG.md
- django_declarative_apis/machinery/filtering.py
> Docs: add comment explaining why `dicts` are excluded from filtering

- CHANGELOG.md
- pyproject.toml
> chore: upgrade django 4.2 LTS (@W-14178534)

- django_declarative_apis/resources/emitters.py
There is a broken link in this project to a blog that does not exist anymore. I replaced it with the internet archive.
http://nadiana.com/python-pickle-insecure --> https://web.archive.org/web/20130423223601/http://nadiana.com/python-pickle-insecure
I found this links using a tool I created called [link-inspector](https://github.com/justindhillon/link-inspector) .  If you find this PR useful, give the repo a :star:
> Fix broken link in emitters.py

- .gitignore
- CHANGELOG.md
- README.md
- django_declarative_apis/events.py
- django_declarative_apis/machinery/tasks.py
- tests/test_events.py
This update introduces the ability to use custom hooks for emitting events in Django projects, providing a flexible mechanism for developers to handle application events outside of New Relic. By configuring a custom hook, you can process events in a way that fits your application's needs, whether it's logging, sending notifications, or integrating with other third-party services.
> Custom Event Hooks Event Emission

- .github/workflows/tests.yml
- django_declarative_apis/authentication/oauthlib/endpoint.py
- django_declarative_apis/authentication/oauthlib/request_validator.py
- django_declarative_apis/machinery/__init__.py
- django_declarative_apis/resources/resource.py
- tests/authentication/oauthlib/test_request_validator.py
[W-17954157](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17954157)
----
- the 404, 429 errors now don't show the full stack traces 
- [old](https://splunk-web-noncore.log-analytics.monitoring.aws-esvc1-useast2.aws.sfdc.is/en-US/app/search/search?sid=1741128748.153747_B07B4BA0-F02B-4D7E-9890-2524097BB5BC) -> 91 log events
- [new](https://splunk-web-noncore.log-analytics.monitoring.aws-esvc1-useast2.aws.sfdc.is/en-US/app/search/search?sid=1741128928.153752_B07B4BA0-F02B-4D7E-9890-2524097BB5BC) -> 11 log events
- coalesce the log lines around failed oauth1 failures (signature and client)
- don't log "shouldn't happen" messages for cases where the consumer key is invalid ( `registers authenticator - bad credentials` e2e test)
- adjust the test Github workflow to test …
> chore: don't log stack traces for client errors @W-17954157

- .bumpversion.cfg
- .gitignore
- docs/source/conf.py
- pyproject.toml
> chore: new version v0.32.0

- django_declarative_apis/machinery/attributes.py
- django_declarative_apis/resources/resource.py
- tests/machinery/test_attributes.py
Work Item: [W-18078839](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18128971)
----
- Add a few docstring and inline comments to modified methods
- Improve boolean type handling with more valid values
- Improve error handling with detailed messages and logging
- Add explicit checks for None request and query_dict
- Improve field name handling with explicit checks
- add unit tests for `RequstField.get_without_default` method
----
> feat: handle request.GET or request.POST being None + a few other improvements  @W-18128971

- .bumpversion.cfg
- CHANGELOG.md
- django_declarative_apis/resources/emitters.py
- django_declarative_apis/resources/resource.py
- docs/source/conf.py
- pyproject.toml
- tests/resources/test_emitters.py
- tests/resources/test_resource.py
> move fix for no_content responses to resource layer
